version: '3.9'

services:
  app:
    image: node:21
    container_name: product-crud-nestjs-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    command: sh -c "npm install --legacy-peer-deps && npm run build && npm run start:dev"
    env_file:
      - .env
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: postgres:15
    container_name: product-crud-postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
